### ISSUE TITLE
IRAF external packages

### ISSUE THREAD

**Issue by fcomeron** [iraf-community/iraf-community.github.io#11]
Hi, I have followed the instructions step by step and I have installed IRAF v2.18 with no problems in my Ubuntu laptop. However I cannot see any of the external packages in astro-iraf. How do I install the complete version (this is, also the external packages)? I did sudo apt install astro-iraf but apparently is not enough. Probably I am missing something basic here. Thanks for the help!

Fernando

**Comment by olebole** [comment]
I guess you installed IRAF from source?

The external packages in the [astro-iraf](https://blends.debian.org/astro/tasks/iraf) are meant to be used together with the IRAF package that comes with Ubuntu, not with a self-compiled one. The best way therefore here would be to remove your local installation and do a `sudo apt install iraf`. If you want to keep the local installation, make sure that you don't have the **iraf** environment variable pointing to it, and that you use `/usr/bin/irafcl` (or `/usr/bin/irafcl -x`) to start IRAF.
